[build]
  base = "."
  publish = "dist"

# Production version, deployed by CI
[context.main]
  command = "npm run build:prod"

# Staging version, deployed by push to develop
[context.develop]
  command = "npm run build:stage"

# Previews for pull requests
[context.deploy-preview]
  command = "npm run build:stage"

# Redirect to main page
[[redirects]]
  from = "/*"
  to = "https://www.wwdcscholars.com/join?utm_medium=referral&utm_source=join"
  status = 302
  force = true

# # Plausible Proxy
# [[redirects]]
#   from = "/stats/api/event"
#   to = "https://plausible.io/api/event"
#   status = 200
#   force = true

# # SPA redirect
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
